---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mgglaweu/public_html/
    - source /home/mgglaweu/nodevenv/repos/mgg-law/20/bin/activate && npm install --include=dev && npm run build
    - /bin/cp -r dist/. /home/mgglaweu/public_html/
