---
deployment:
  tasks:
    - /home/mgglaweu/nodevenv/repos/mgg-law/20/bin/npm install
    - /home/mgglaweu/nodevenv/repos/mgg-law/20/bin/npm run build
    - /bin/cp -rf dist/* /home/mgglaweu/public_html/
