---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mgglaweu/public_html/
    - /home/mgglaweu/nodevenv/repos/mgg-law/20/bin/npm ci
    - /home/mgglaweu/nodevenv/repos/mgg-law/20/bin/npm run build
    - /bin/cp -r dist/. /home/mgglaweu/public_html/
